basePath: /
definitions:
  postgres.Person:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a REST API for managing people.
  title: TestRest API
  version: "1.0"
paths:
  /delete:
    delete:
      description: DeletePerson Delete a person by their ID
      parameters:
      - description: Person ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Deleted person by ID
          schema:
            type: string
        "400":
          description: Invalid ID parameter
          schema:
            type: string
        "500":
          description: Failed to delete person
          schema:
            type: string
      summary: Delete person
      tags:
      - people
  /get:
    get:
      consumes:
      - application/json
      description: GetInfo Get a person's details by their ID
      parameters:
      - description: Person ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.Person'
        "400":
          description: Invalid ID parameter
          schema:
            type: string
        "500":
          description: Failed to get person
          schema:
            type: string
      summary: Get person info
      tags:
      - people
  /post:
    post:
      description: InsertPerson Add a new person to the database
      parameters:
      - description: Person's name
        in: query
        name: name
        required: true
        type: string
      - description: Person's surname
        in: query
        name: surname
        required: true
        type: string
      - description: Person's patronymic
        in: query
        name: patronymic
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.Person'
        "500":
          description: Failed to insert person
          schema:
            type: string
      summary: Insert person
      tags:
      - people
  /put:
    put:
      description: UpdatePerson Update a person's details by their ID
      parameters:
      - description: Person ID
        in: query
        name: id
        required: true
        type: integer
      - description: Person's name
        in: query
        name: name
        required: true
        type: string
      - description: Person's surname
        in: query
        name: surname
        required: true
        type: string
      - description: Person's patronymic
        in: query
        name: patronymic
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.Person'
        "400":
          description: Invalid ID parameter
          schema:
            type: string
        "500":
          description: Failed to update person
          schema:
            type: string
      summary: Update person
      tags:
      - people
swagger: "2.0"
